package by.epam.auctionhouse.command;

public enum CommandName {
SIGN_IN,SIGN_OUT,NO_SUCH_COMMAND,LOCALIZATION,REGISTRATION,
ADD_AUCTION,EDIT_AUCTION,DELETE_AUCTION,
ADD_LOT,GO_TO_ADMIN_PAGE,GO_TO_ADD_AUCTION_PAGE,GO_TO_EDIT_PAGE,
GO_TO_MAIN_PAGE, GO_TO_AUCTION_PAGE
}
