package by.epam.auctionhouse.command;

public enum CommandName {
SIGN_IN,SIGN_OUT,NO_SUCH_COMMAND,LOCALIZATION,REGISTRATION,
ADD_AUCTION,EDIT_AUCTION,DELETE_AUCTION,
ADD_LOT,GO_TO_ADMIN_PAGE,GO_TO_ADD_AUCTION_PAGE,GO_TO_EDIT_PAGE,
GO_TO_MAIN_PAGE, GO_TO_AUCTION_PAGE, GO_TO_CLIENT_PAGE, GO_TO_AUCTIONS_PAGE, GO_TO_LOTS_PAGE, GO_TO_CLIENTS_PAGE, GO_TO_AUCTION_BETS_PAGE,
PLACE_ENGLISH_BET,PLACE_BLITZ_BET,CHANGE_USER_STATUS, SET_AUCTION_WINNER
}
